### ISSUE TITLE
Error: Shell /usr/bin/fish must exist

### ISSUE THREAD

**Issue by blandman** [petems/petems-fish#1]
When attempting to set the shell on a fresh host that hasn't installed the fish package, I've run into a dependency nightmare, unable to find the correct way to optionally set the shell. This is probably a lack of my understanding on how to use the module.

Here's my .pp file

```
include ::fish

user { 'root':
         ensure        => 'present',
         shell         => '/usr/bin/fish'
 }
```

Doing this yields 
```
Error: Shell /usr/bin/fish must exist
Error: /Stage[main]/Psd_default/User[root]/shell: change from /bin/bash to /usr/bin/fish failed: Shell /usr/bin/fish must exist
```

I've tried a number of conditional statements, all leading to failures because fish somehow depends on the root user definition. 

```
 exec {"check_fish":
          command => 'test -f /usr/bin/fish',
          user  => root,
          unless => 'test -f /usr/bin/fish',
          path   => ['/usr/bin','/usr/sbin','/bin','/sbin'],
}

user { 'root':
         ensure        => 'present',
         shell         => '/usr/bin/fish',
         require    => Exec["check_fish"]
 }
```

But doing a require => Exec["check_fish"] yields the same result, no matter the outcome of the Exec. If the Exec doesn't trigger the User, fish somehow depends on that user and fails to install.
Simply Requiring anything from the fish class yields a dependency loop. 

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Exec[fish-add-apt-repository-ppa:fish-shell/release-2] => Class[Fish::Repo::Ubuntu] => Class[Fish::Repo] => Class[Fish::Repo] => Class[Fish::Install] => Package[fish] => Class[Fish::Install] => Class[Fish] => Class[Fish] => User[root] => Exec[fish-add-apt-repository-ppa:fish-shell/release-2])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

**Comment by petems** [comment]
@blandman Would this do the trick:

```
user {'root':
 ensure => 'present',
 shell    => '/usr/bin/fish'
 require => Class['::fish']
}
```

This would the Fish class have completed before trying to change the shell, meaning the package would be installed and it wouldn't fail 👍

**Comment by blandman** [comment]
I tried this in my many attempts, requiring anything from fish yields this message:

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Exec[fish-add-apt-repository-ppa:fish-shell/release-2] => Class[Fish::Repo::Ubuntu] => Class[Fish::Repo] => Class[Fish::Repo] => Class[Fish::Install] => Package[fish] => Class[Fish::Install] => Class[Fish] => Class[Fish] => User[root] => Exec[fish-add-apt-repository-ppa:fish-shell/release-2])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

this `Exec[fish-add-apt-repository-ppa:fish-shell/release-2]` is always where the dependency loop happens, it seems the User[root] is always just before the last Exec.

I was able to work around failures by storing the shell as a variable, then checking facts from apt for installed packages and if fish was present, set the shell to fish. This isn't ideal as some clients are redhat. I found an inventory fact script but this wasn't populating, even after several hours.

**Comment by petems** [comment]
@blandman That is one way, you shouldn't need the fact tbh. The `sw_inv` fact will slow down Puppet runs a bit.

Can you show me the full catalog that you're using that causes that dependancy cycle?

**Comment by blandman** [comment]
It will cause slow downs when using like this? Or in general? I'll need the sw_inv for other purposes anyways.

```
class psd_default {
        include puppet_agent
        include "fish"
        class { '::ntp':
                servers => [ '10.0.0.7', '0.amazon.pool.ntp.org', '1.amazon.pool.ntp.org', '2.amazon.pool.ntp.org', '3.amazon.pool.ntp.org' ],
        }

        $inv = $facts["sw_inv"]

        if has_key($inv, 'fish'){
                $rootShell = "/usr/bin/fish"
                notify {"I have fish installed <3":}
        } else {
                $rootShell = "/bin/bash"
        }

        user { 'root':
          ensure        => 'present',
          shell         => '/usr/bin/fish',
          require       => Class["::fish"]
        }

        include 'key'
}
```

At first I thought maybe it was my key class (rsa keys) running before the root user, but I get the same dependency cycle when including it after.

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Exec[fish-add-apt-repository-ppa:fish-shell/release-2] => Class[Fish::Repo::Ubuntu] => Class[Fish::Repo] => Class[Fish::Repo] => Class[Fish::Install] => Package[fish] => Class[Fish::Install] => Class[Fish] => Class[Fish] => User[root] => Exec[fish-add-apt-repository-ppa:fish-shell/release-2])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

Should I try the --graph to generate a .dot file?

**Comment by blandman** [comment]
I don't get a dependency cycle error if I use:

```
user { 'root':
          ensure        => 'present',
          shell         => $rootShell,
          require       => Exec['fish-add-apt-repository-ppa:fish-shell/release-2']
}
```

However this would be different per redhat/debian?

**Comment by petems** [comment]
For `sw_inv`, any fact that takes some time to return (like package version) will slow down your Puppet runs, but if you're already using it, it shouldn't matter.

I think the dependancy error is related to the loose exec in the Ubuntu class, can you try with the latest commit from master: https://github.com/petems/petems-fish/commit/840458c26759a71a8b50047206f1b1526f527ac2

If that works for you, I'll tag and release.

If that doesn't work, can you try this commit: 5ca4f19aed976a0893e9b46b8c09ec97c5b84586

If not, can you try:

```
user { 'root':
  ensure        => 'present',
  shell           => $rootShell,
  require       => Class['::fish::package']
}
```

Also, I'd recommend changing the parameter name from `rootShell` to `root_shell`, the style guide recomends using underscores over camelcase 👍

**Comment by blandman** [comment]
It looks like that did the trick!

I couldn't use `Class['::fish::package']` because `Invalid relationship: User[root] { require => Class[Fish::Package] }, because Class[Fish::Package] doesn't seem to be in the catalog`
but this worked

```
user { 'root':
          ensure        => 'present',
          shell         => $root_shell,
          require       => Class['::fish']
}
```

**Comment by petems** [comment]
@blandman Awesome! Which commit worked with that? Was that 5ca4f19 or 840458c?

**Comment by blandman** [comment]
I just pulled from master, so 840458c 
[(Previously I was using the version on Forge)](https://forge.puppet.com/petems/fish)

**Comment by petems** [comment]
Oh cool, so just the latest master worked, that's awesome.

It makes sense, as the exec would be lose in the class, whereas using the apt type would be contained by the class contain 👍 

I'll release a new version to the forge for that 👍

**Comment by petems** [comment]
Released as https://forge.puppet.com/v3/files/petems-fish-0.2.0.tar.gz

Glad I could help! 😄

**Comment by petems** [comment]
@blandman

**Comment by blandman** [comment]
@petems Wow amazing work! Thank you so much, that commit is wonderful 👍 👍 👍
